pub mod account;
pub mod account_data;
pub mod alias;
pub mod appservice;
pub mod backup;
pub mod capabilities;
pub mod context;
pub mod device;
pub mod directory;
pub mod filter;
pub mod keys;
pub mod media;
pub mod media_legacy;
pub mod membership;
pub mod message;
pub mod openid;
pub mod presence;
pub mod profile;
pub mod push;
pub mod read_marker;
pub mod redact;
pub mod register;
pub mod relations;
pub mod report;
pub mod room;
pub mod search;
pub mod send;
pub mod session;
pub mod space;
pub mod state;
pub mod sync;
pub mod tag;
pub mod thirdparty;
pub mod threads;
pub mod to_device;
pub mod typing;
pub mod unstable;
pub mod unversioned;
pub mod user_directory;
pub mod voip;
pub mod well_known;

mod utils;

pub use account::*;
pub use account_data::*;
pub use alias::*;
pub use appservice::*;
pub use backup::*;
pub use capabilities::*;
pub use context::*;
pub use device::*;
pub use directory::*;
pub use filter::*;
pub use keys::*;
pub use media::*;
pub use media_legacy::*;
pub use membership::*;
pub use message::*;
pub use openid::*;
pub use presence::*;
pub use profile::*;
pub use push::*;
pub use read_marker::*;
pub use redact::*;
pub use register::*;
pub use relations::*;
pub use report::*;
pub use room::*;
pub use search::*;
pub use send::*;
pub use session::*;
pub use space::*;
pub use state::*;
pub use sync::*;
pub use tag::*;
pub use thirdparty::*;
pub use threads::*;
pub use to_device::*;
pub use typing::*;
pub use unstable::*;
pub use unversioned::*;
pub use user_directory::*;
pub use voip::*;
pub use well_known::*;

/// generated device ID length
const DEVICE_ID_LENGTH: usize = 10;

/// generated user access token length
const TOKEN_LENGTH: usize = tuwunel_service::users::device::TOKEN_LENGTH;

/// generated user session ID length
const SESSION_ID_LENGTH: usize = tuwunel_service::uiaa::SESSION_ID_LENGTH;
